name: Test Action

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  test-community-maps-2:
    runs-on: ubuntu-latest
    env:
      MOD_NAME: community-maps-2
      MOD_VERSION: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: 0ad-matters/gh-action-build-pyromod@v1
      with:
        name: ${{ env.MOD_NAME }}
        version: ${{ env.MOD_VERSION }}
        directory: 'test/${{ env.MOD_NAME }}'
    - run: rm -rf /output/*
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Use action from self
      uses: ./
      with:
        name: ${{ env.MOD_NAME }}
        version: ${{ env.MOD_VERSION }}
        directory: 'test/${{ env.MOD_NAME }}'
        remove_from_pyromod: '/maps/random/* /.git* art/particles/*'
